assistant-output-color: '#00FF00'  # Bright Green - very readable
tool-output-color: '#FFFFFF'       # White - maximum readability
tool-error-color: '#FF0000'        # Red - clear error indication
tool-warning-color: '#FFFF00'      # Yellow - clear warning indication
user-input-color: '#00FFFF'        # Cyan - distinctive and readable
