hostname-fg = "ebdbb2"
hostname-bg = "d65d0e"
success-symbol-fg = "282828"
success-symbol-bg = "98971a"
error-symbol-fg = "ebdbb2"
error-symbol-bg = "cc241d"
nix-prompt-fg = "282828"
nix-prompt-bg = "8ec07c"
git-status-fg = "ebdbb2"
git-status-bg = "689d6a"
git-state-fg = "ebdbb2"
git-state-bg = "689d6a"
git-branch-fg = "ebdbb2"
git-branch-bg = "689d6a"
directory-fg = "ebdbb2"
directory-bg = "458588"
time-fg = "ebdbb2"
time-bg = "b16286"
user-fg = "ebdbb2"
user-bg = "cc241d"
root-user-fg = "ebdbb2"
root-user-bg = "fb4934"
