-- This file is automatically generated. Do not edit it manually.
-- To change the colors, edit colorscheme/colors.toml and run
-- colorscheme/generate_wezterm_theme.py

return {
    background = "#282828",
    foreground = "#ebdbb2",
    cursor_bg = "#d5c4a1",
    cursor_fg = "#282828",
    selection_bg = "#504945",
    selection_fg = "#ebdbb2",
    ansi = {
        "#282828", -- black
        "#c23422", -- red
        "#9ca826", -- green
        "#e29e26", -- yellow
        "#4d918e", -- blue
        "#b57990", -- magenta
        "#70a778", -- cyan
        "#a89984", -- white
    },
    brights = {
        "#928a7e", -- bright black
        "#fc5944", -- bright red
        "#b9c92a", -- bright green
        "#fac440", -- bright yellow
        "#8aacaa", -- bright blue
        "#d79aa6", -- bright magenta
        "#95c486", -- bright cyan
        "#ebdbb2", -- bright white
    },
}