# NVIM-SPECIFIC COLORS
[nvim]
# Base gruvbox colors
dark0 = "282828"
dark1 = "3c3836"
dark2 = "504945"
dark3 = "665c54"
dark4 = "7c6f64"
light0 = "fbf1c7"
light1 = "ebdbb2"
light2 = "d5c4a1"
light3 = "bdae93"
light4 = "a89984"

# Standard colors
bright_red = "fc5944"
bright_green = "b9c92a"
bright_yellow = "fac440"
bright_blue = "8aacaa"
bright_purple = "d79aa6"
bright_aqua = "95c486"
bright_orange = "fe8c29"

# Neutral colors
neutral_red = "c23422"
neutral_green = "9ca826"
neutral_yellow = "e29e26"
neutral_blue = "4d918e"
neutral_purple = "b57990"
neutral_aqua = "70a778"

# Faded colors
faded_red = "a41b10"
faded_green = "7e7a16"
faded_yellow = "bb7d1c"
faded_blue = "247b7a"
faded_purple = "954978"
faded_aqua = "4b865e"
faded_orange = "b74b12"

# Light mode specific colors
light_red = "ae1010"
light_green = "7f8016"
light_aqua = "467d5e"

# Gray
gray = "928a7e"

# CROSS-TOOL SEMANTIC COLORS
# For consistency across different tools
[semantic]
semantic_success = "9ca826"
semantic_error = "c23422"
semantic_warning = "e29e26"
semantic_info = "4d918e"
semantic_hint = "70a778"

# starship colors
[starship]
default-fg = "ebdbb2"
hostname-bg = "d65d0e"
success-symbol-fg = "282828"
success-symbol-bg = "98971a"
error-symbol-bg = "cc241d"
nix-prompt-fg = "282828"
nix-prompt-bg = "8ec07c"
git-status-bg = "689d6a"
git-state-bg = "689d6a"
git-branch-bg = "689d6a"
directory-bg = "458588"
time-bg = "b16286"
user-bg = "cc241d"
root-user-bg = "fb4934"

# aider colors
[aider]
assistant-output-color = '98c379'
tool-output-color = 'abb2bf'
tool-error-color = 'e06c75'
tool-warning-color = 'e5c07b'
user-input-color = '61afef'
completion-menu-color = '98c379'
completion-menu-bg-color = '282c34'
completion-menu-current-color = 'c678dd'
completion-menu-current-bg-color = '3e4452'

# delta colors
[delta]
delta-plus-bg = "2d472d"
delta-minus-bg = "422a2a"
delta-plus-fg = "c8d8a8"
delta-minus-fg = "e8a8a8"
delta-plus-non-emph-fg = "a8b888"
delta-minus-non-emph-fg = "c88888"