# NVIM-SPECIFIC COLORS
[nvim]
# Base gruvbox colors
dark0 = "282828"
dark1 = "3c3836"
dark2 = "504945"
dark3 = "665c54"
dark4 = "7c6f64"
light0 = "fbf1c7"
light1 = "ebdbb2"
light2 = "d5c4a1"
light3 = "bdae93"
light4 = "a89984"

# Standard colors
bright_red = "fc5944"
bright_green = "b9c92a"
bright_yellow = "fac440"
bright_blue = "8aacaa"
bright_purple = "d79aa6"
bright_aqua = "95c486"
bright_orange = "fe8c29"

# Neutral colors
neutral_red = "c23422"
neutral_green = "9ca826"
neutral_yellow = "e29e26"
neutral_blue = "4d918e"
neutral_purple = "b57990"
neutral_aqua = "70a778"

# Faded colors
faded_red = "a41b10"
faded_green = "7e7a16"
faded_yellow = "bb7d1c"
faded_blue = "247b7a"
faded_purple = "954978"
faded_aqua = "4b865e"
faded_orange = "b74b12"

# Light mode specific colors
light_red = "ae1010"
light_green = "7f8016"
light_aqua = "467d5e"

# Gray
gray = "928a7e"

# CROSS-TOOL SEMANTIC COLORS
# For consistency across different tools
[semantic]
semantic_success = "9ca826"
semantic_error = "c23422"
semantic_warning = "e29e26"
semantic_info = "4d918e"
semantic_hint = "70a778"

# starship colors
[starship]
default-fg = "ebdbb2"
hostname-bg = "d65d0e"
success-symbol-fg = "282828"
success-symbol-bg = "98971a"
error-symbol-bg = "cc241d"
nix-prompt-fg = "282828"
nix-prompt-bg = "8ec07c"
git-status-bg = "689d6a"
git-state-bg = "689d6a"
git-branch-bg = "689d6a"
directory-bg = "458588"
time-bg = "b16286"
user-bg = "cc241d"
root-user-bg = "fb4934"

# aider colors
[aider]
assistant-output-color = '98c379'
tool-output-color = 'abb2bf'
tool-error-color = 'e06c75'
tool-warning-color = 'e5c07b'
user-input-color = '61afef'
completion-menu-color = '98c379'
completion-menu-bg-color = '282c34'
completion-menu-current-color = 'c678dd'
completion-menu-current-bg-color = '3e4452'

# delta colors
[delta]
delta-plus-bg = "2d472d"
delta-minus-bg = "422a2a"
delta-plus-fg = "c8d8a8"
delta-minus-fg = "e8a8a8"
delta-plus-non-emph-fg = "a8b888"
delta-minus-non-emph-fg = "c88888"

[zellij]
text_unselected_base = "ebdbb2"
text_unselected_background = "3c3836"
text_selected_base = "fbf1c7"
text_selected_background = "504945"
text_unselected_emphasis_0 = "fe8019"
text_unselected_emphasis_1 = "8ec07c"
text_unselected_emphasis_2 = "fabd2f"
text_unselected_emphasis_3 = "d3869b"
text_selected_emphasis_0 = "fe8019"
text_selected_emphasis_1 = "8ec07c"
text_selected_emphasis_2 = "fabd2f"
text_selected_emphasis_3 = "d3869b"
ribbon_selected_base = "282828"
ribbon_selected_background = "83a598"
ribbon_selected_emphasis_0 = "cc241d"
ribbon_selected_emphasis_1 = "fe8019"
ribbon_selected_emphasis_2 = "b16286"
ribbon_selected_emphasis_3 = "83a59b"
ribbon_unselected_base = "282828"
ribbon_unselected_background = "ebdbb2"
ribbon_unselected_emphasis_0 = "cc241d"
ribbon_unselected_emphasis_1 = "fbf1c7"
ribbon_unselected_emphasis_2 = "83a598"
ribbon_unselected_emphasis_3 = "b16286"
table_title_base = "fabd2f"
table_title_background = "0"
table_title_emphasis_0 = "fe8019"
table_title_emphasis_1 = "8ec07c"
table_title_emphasis_2 = "fabd2f"
table_title_emphasis_3 = "d3869b"
table_cell_selected_base = "fbf1c7"
table_cell_selected_background = "504945"
table_cell_selected_emphasis_0 = "fe8019"
table_cell_selected_emphasis_1 = "8ec07c"
table_cell_selected_emphasis_2 = "fabd2f"
table_cell_selected_emphasis_3 = "d3869b"
table_cell_unselected_base = "ebdbb2"
table_cell_unselected_background = "3c3836"
table_cell_unselected_emphasis_0 = "fe8019"
table_cell_unselected_emphasis_1 = "8ec07c"
table_cell_unselected_emphasis_2 = "fabd2f"
table_cell_unselected_emphasis_3 = "d3869b"
list_selected_base = "fbf1c7"
list_selected_background = "504945"
list_selected_emphasis_0 = "fe8019"
list_selected_emphasis_1 = "8ec07c"
list_selected_emphasis_2 = "fabd2f"
list_selected_emphasis_3 = "d3869b"
list_unselected_base = "ebdbb2"
list_unselected_background = "3c3836"
list_unselected_emphasis_0 = "fe8019"
list_unselected_emphasis_1 = "8ec07c"
list_unselected_emphasis_2 = "fabd2f"
list_unselected_emphasis_3 = "d3869b"
frame_selected_base = "fabd2f"
frame_selected_background = "0"
frame_selected_emphasis_0 = "fe8019"
frame_selected_emphasis_1 = "8ec07c"
frame_selected_emphasis_2 = "d3869b"
frame_selected_emphasis_3 = "0"
frame_highlight_base = "fe8019"
frame_highlight_background = "0"
frame_highlight_emphasis_0 = "fe8019"
frame_highlight_emphasis_1 = "fe8019"
frame_highlight_emphasis_2 = "fe8019"
frame_highlight_emphasis_3 = "fe8019"
exit_code_success_base = "b8bb26"
exit_code_success_background = "0"
exit_code_success_emphasis_0 = "8ec07c"
exit_code_success_emphasis_1 = "3c3836"
exit_code_success_emphasis_2 = "d3869b"
exit_code_success_emphasis_3 = "83a598"
exit_code_error_base = "fb4934"
exit_code_error_background = "0"
exit_code_error_emphasis_0 = "d79921"
exit_code_error_emphasis_1 = "0"
exit_code_error_emphasis_2 = "0"
exit_code_error_emphasis_3 = "0"
multiplayer_user_colors_player_1 = "d3869b"
multiplayer_user_colors_player_2 = "83a598"
multiplayer_user_colors_player_3 = "0"
multiplayer_user_colors_player_4 = "d79921"
multiplayer_user_colors_player_5 = "8ec07c"
multiplayer_user_colors_player_6 = "0"
multiplayer_user_colors_player_7 = "cc241d"
multiplayer_user_colors_player_8 = "0"
multiplayer_user_colors_player_9 = "0"
multiplayer_user_colors_player_10 = "0"
