# Base gruvbox colors for Neovim
dark0 = "282828"
dark1 = "3c3836"
dark2 = "504945"
dark3 = "665c54"
dark4 = "7c6f64"
light0 = "fbf1c7"
light1 = "ebdbb2"
light2 = "d5c4a1"
light3 = "bdae93"
light4 = "a89984"

# Standard colors
bright_red = "fb4934"
bright_green = "b8bb26"
bright_yellow = "fabd2f"
bright_blue = "83a598"
bright_purple = "d3869b"
bright_aqua = "8ec07c"
bright_orange = "fe8019"

# Neutral colors
neutral_red = "cc241d"
neutral_green = "98971a"
neutral_yellow = "d79921"
neutral_blue = "458588"
neutral_purple = "b16286"
neutral_aqua = "689d6a"

# Faded colors
faded_red = "9d0006"
faded_green = "79740e"
faded_yellow = "b57614"
faded_blue = "076678"
faded_purple = "8f3f71"
faded_aqua = "427b58"
faded_orange = "af3a03"

# Light mode specific colors
light_red = "9d0006"
light_green = "79740e"
light_aqua = "427b58"

# Gray
gray = "928374"

# starship colors
default-fg = "ebdbb2"
hostname-bg = "d65d0e"
success-symbol-fg = "282828"
success-symbol-bg = "98971a"
error-symbol-bg = "cc241d"
nix-prompt-fg = "282828"
nix-prompt-bg = "8ec07c"
git-status-bg = "689d6a"
git-state-bg = "689d6a"
git-branch-bg = "689d6a"
directory-bg = "458588"
time-bg = "b16286"
user-bg = "cc241d"
root-user-bg = "fb4934"

# aider colors
assistant-output-color = '98c379'
tool-output-color = 'abb2bf'
tool-error-color = 'e06c75'
tool-warning-color = 'e5c07b'
user-input-color = '61afef'
completion-menu-color = '98c379'
completion-menu-bg-color = '282c34'
completion-menu-current-color = 'c678dd'
completion-menu-current-bg-color = '3e4452'

# delta colors
delta-plus-bg = "2d472d"
delta-minus-bg = "422a2a"
delta-plus-fg = "c8d8a8"
delta-minus-fg = "e8a8a8"
delta-plus-non-emph-fg = "a8b888"
delta-minus-non-emph-fg = "c88888"
